### ISSUE TITLE
Authentication API

### ISSUE THREAD

**Issue by michealsong** [dev-wirelessbro/server#1]
## login 
- username
- password

API:
- [ ] POST login

## Signup
STEP 1: create account
- username
- password
- email
- telephone

STEP 2: add company information
- company name
- company address
- seller permit
- category
- subcategory
- budget per month
- budget per year

STEP 3: legal agreement

API:
- [ ] POST create account
- [ ] PUT   add company information
- [ ] Get    retrieve category
- [ ] Get    retrieve subcategory

## Logout

API:
- [ ] POST logout

**Comment by dyguan372** [comment]
STEP 4: administrator review
API: /api/user/activate/:userId
       /api/user/deactivate/:userId
       /api/user for query users, e.g. /api/user?active=false
